workflows:
  ios-build:
    name: iOS Expo Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Expo project
        script: npx expo prebuild && npx expo run:ios --no-install
    artifacts:
      - ios/build/**/*.ipa
    publishing:
      email:
        recipients:
          - dilhan.bzkrt@gmail.com
